-- ProdClin — v6.44.0 — Importação em lote da lista de materiais enviada
-- pelo usuário (83 itens): cadastra no catálogo (Estoque mínimo já vem
-- preenchido) e lança o Estoque Inicial como uma entrada (lote), sem
-- fornecedor/NF vinculados (é o saldo inicial, não veio de uma nota
-- específica). Unidade não veio na lista original — todos entram como
-- 'unidade'; ajuste depois pela Listagem (Editar) se algum item for
-- caixa/pacote/frasco etc.

-- 1) Cadastro dos materiais
insert into materiais (nome, unidade, estoque_minimo) values
  ('Agulha 0,7 x 25', 'unidade', 100),
  ('Agulha 25 x 0,80', 'unidade', 100),
  ('Agulha 1,20 x 40', 'unidade', 100),
  ('Agulha 0,45 x 13', 'unidade', 100),
  ('Scalp 25', 'unidade', 100),
  ('Scalp 27', 'unidade', 100),
  ('Fita microporosa', 'unidade', 5),
  ('Esparadrapo', 'unidade', 5),
  ('Água para injeção 10 ml', 'unidade', 50),
  ('Glicose 10 ML', 'unidade', 30),
  ('Atadura crepom', 'unidade', 1),
  ('Avental – pacote', 'unidade', 5),
  ('Lençol com elástico', 'unidade', 10),
  ('Avental Dr.', 'unidade', 5),
  ('Rolo de algodão', 'unidade', 1),
  ('Avental técnicos', 'unidade', 5),
  ('Touca descartável', 'unidade', 5),
  ('Propé', 'unidade', 5),
  ('Cateter tipo óculos', 'unidade', 30),
  ('Máscara', 'unidade', 20),
  ('Seringa 5 ml', 'unidade', 200),
  ('Teste de H. pylori', 'unidade', 5),
  ('Fentalina', 'unidade', 50),
  ('Óculos de proteção', 'unidade', 1),
  ('Buscopan', 'unidade', 100),
  ('Midazolam', 'unidade', 50),
  ('Succitrat', 'unidade', 5),
  ('Propofol', 'unidade', 5),
  ('Etilefrina', 'unidade', 5),
  ('Haloperidol', 'unidade', 5),
  ('Furosemida', 'unidade', 4),
  ('Atropina', 'unidade', 4),
  ('Epinefrina', 'unidade', 50),
  ('Vaselina', 'unidade', 1),
  ('Silicone para endoscópio', 'unidade', 1),
  ('Phosphoenema', 'unidade', 1),
  ('Seringa de vidro', 'unidade', 1),
  ('Algodão / poliéster', 'unidade', 10),
  ('Trombofob  Gel', 'unidade', 1),
  ('Torneira 3 vias', 'unidade', 3),
  ('Curativo adesivo', 'unidade', 1),
  ('Luva M', 'unidade', 5),
  ('Luva P', 'unidade', 5),
  ('Luva G', 'unidade', 5),
  ('Luva cirúrgica', 'unidade', 3),
  ('Sonda  Enteral', 'unidade', 2),
  ('Teste de lactase', 'unidade', 12),
  ('Frutose', 'unidade', 12),
  ('Luva azul', 'unidade', 2),
  ('Máscara descartável', 'unidade', 4),
  ('Cateter 22', 'unidade', 100),
  ('Cateter 14', 'unidade', 50),
  ('Cateter 16', 'unidade', 100),
  ('Cateter 18', 'unidade', 50),
  ('Cateter 20', 'unidade', 50),
  ('Cateter 24', 'unidade', 100),
  ('Agulha 13x 0,45', 'unidade', 300),
  ('Agulha 40x1,20', 'unidade', 300),
  ('Seringa 1 ml', 'unidade', 20),
  ('Seringa 3 ml', 'unidade', 300),
  ('Seringa 60 ml', 'unidade', 1),
  ('Seringa 20 ml', 'unidade', 100),
  ('Seringa 10 ml', 'unidade', 100),
  ('Manitol', 'unidade', 50),
  ('Glicose 500 ml', 'unidade', 10),
  ('Álcool 70%', 'unidade', 10),
  ('Xylestesin Spray', 'unidade', 2),
  ('Lactuose', 'unidade', 2),
  ('Simeticona 75 mg/ml', 'unidade', 20),
  ('Envelope para esterilização', 'unidade', 1),
  ('Escovinha', 'unidade', 5),
  ('Equipo macrogotas', 'unidade', 5),
  ('Gel para ultrassom', 'unidade', 1),
  ('Detergente enzimático', 'unidade', 2),
  ('Iodo', 'unidade', 1),
  ('Lidocaina gel', 'unidade', 30),
  ('Cloreto de sódio 250 ml', 'unidade', 50),
  ('Soro cloreto de sódio 100 ml', 'unidade', 50),
  ('Soro cloreto de sódio 500 ml', 'unidade', 60),
  ('Água para injeção', 'unidade', 60),
  ('Solução Ringer com lactato 500 ml', 'unidade', 60),
  ('Diazepam', 'unidade', 3),
  ('Papel lençol', 'unidade', 20);

-- 2) Estoque inicial de cada um (vira um lote, sem fornecedor/NF)
insert into estoque_lotes (material_id, quantidade_entrada, quantidade_atual, data_entrada) values
  ((select id from materiais where nome = 'Agulha 0,7 x 25' order by criado_em desc limit 1), 200, 200, current_date),
  ((select id from materiais where nome = 'Agulha 25 x 0,80' order by criado_em desc limit 1), 200, 200, current_date),
  ((select id from materiais where nome = 'Agulha 1,20 x 40' order by criado_em desc limit 1), 300, 300, current_date),
  ((select id from materiais where nome = 'Agulha 0,45 x 13' order by criado_em desc limit 1), 100, 100, current_date),
  ((select id from materiais where nome = 'Scalp 25' order by criado_em desc limit 1), 200, 200, current_date),
  ((select id from materiais where nome = 'Scalp 27' order by criado_em desc limit 1), 200, 200, current_date),
  ((select id from materiais where nome = 'Fita microporosa' order by criado_em desc limit 1), 10, 10, current_date),
  ((select id from materiais where nome = 'Esparadrapo' order by criado_em desc limit 1), 15, 15, current_date),
  ((select id from materiais where nome = 'Água para injeção 10 ml' order by criado_em desc limit 1), 110, 110, current_date),
  ((select id from materiais where nome = 'Glicose 10 ML' order by criado_em desc limit 1), 70, 70, current_date),
  ((select id from materiais where nome = 'Atadura crepom' order by criado_em desc limit 1), 4, 4, current_date),
  ((select id from materiais where nome = 'Avental – pacote' order by criado_em desc limit 1), 7, 7, current_date),
  ((select id from materiais where nome = 'Lençol com elástico' order by criado_em desc limit 1), 23, 23, current_date),
  ((select id from materiais where nome = 'Avental Dr.' order by criado_em desc limit 1), 5, 5, current_date),
  ((select id from materiais where nome = 'Rolo de algodão' order by criado_em desc limit 1), 2, 2, current_date),
  ((select id from materiais where nome = 'Avental técnicos' order by criado_em desc limit 1), 7, 7, current_date),
  ((select id from materiais where nome = 'Touca descartável' order by criado_em desc limit 1), 11, 11, current_date),
  ((select id from materiais where nome = 'Propé' order by criado_em desc limit 1), 9, 9, current_date),
  ((select id from materiais where nome = 'Cateter tipo óculos' order by criado_em desc limit 1), 70, 70, current_date),
  ((select id from materiais where nome = 'Máscara' order by criado_em desc limit 1), 22, 22, current_date),
  ((select id from materiais where nome = 'Seringa 5 ml' order by criado_em desc limit 1), 434, 434, current_date),
  ((select id from materiais where nome = 'Teste de H. pylori' order by criado_em desc limit 1), 12, 12, current_date),
  ((select id from materiais where nome = 'Fentalina' order by criado_em desc limit 1), 100, 100, current_date),
  ((select id from materiais where nome = 'Óculos de proteção' order by criado_em desc limit 1), 3, 3, current_date),
  ((select id from materiais where nome = 'Buscopan' order by criado_em desc limit 1), 200, 200, current_date),
  ((select id from materiais where nome = 'Midazolam' order by criado_em desc limit 1), 100, 100, current_date),
  ((select id from materiais where nome = 'Succitrat' order by criado_em desc limit 1), 10, 10, current_date),
  ((select id from materiais where nome = 'Propofol' order by criado_em desc limit 1), 10, 10, current_date),
  ((select id from materiais where nome = 'Etilefrina' order by criado_em desc limit 1), 12, 12, current_date),
  ((select id from materiais where nome = 'Haloperidol' order by criado_em desc limit 1), 10, 10, current_date),
  ((select id from materiais where nome = 'Furosemida' order by criado_em desc limit 1), 8, 8, current_date),
  ((select id from materiais where nome = 'Atropina' order by criado_em desc limit 1), 8, 8, current_date),
  ((select id from materiais where nome = 'Epinefrina' order by criado_em desc limit 1), 50, 50, current_date),
  ((select id from materiais where nome = 'Vaselina' order by criado_em desc limit 1), 2, 2, current_date),
  ((select id from materiais where nome = 'Silicone para endoscópio' order by criado_em desc limit 1), 1, 1, current_date),
  ((select id from materiais where nome = 'Phosphoenema' order by criado_em desc limit 1), 2, 2, current_date),
  ((select id from materiais where nome = 'Seringa de vidro' order by criado_em desc limit 1), 1, 1, current_date),
  ((select id from materiais where nome = 'Algodão / poliéster' order by criado_em desc limit 1), 24, 24, current_date),
  ((select id from materiais where nome = 'Trombofob  Gel' order by criado_em desc limit 1), 3, 3, current_date),
  ((select id from materiais where nome = 'Torneira 3 vias' order by criado_em desc limit 1), 6, 6, current_date),
  ((select id from materiais where nome = 'Curativo adesivo' order by criado_em desc limit 1), 2, 2, current_date),
  ((select id from materiais where nome = 'Luva M' order by criado_em desc limit 1), 25, 25, current_date),
  ((select id from materiais where nome = 'Luva P' order by criado_em desc limit 1), 17, 17, current_date),
  ((select id from materiais where nome = 'Luva G' order by criado_em desc limit 1), 17, 17, current_date),
  ((select id from materiais where nome = 'Luva cirúrgica' order by criado_em desc limit 1), 6, 6, current_date),
  ((select id from materiais where nome = 'Sonda  Enteral' order by criado_em desc limit 1), 4, 4, current_date),
  ((select id from materiais where nome = 'Teste de lactase' order by criado_em desc limit 1), 24, 24, current_date),
  ((select id from materiais where nome = 'Frutose' order by criado_em desc limit 1), 12, 12, current_date),
  ((select id from materiais where nome = 'Luva azul' order by criado_em desc limit 1), 4, 4, current_date),
  ((select id from materiais where nome = 'Máscara descartável' order by criado_em desc limit 1), 8, 8, current_date),
  ((select id from materiais where nome = 'Cateter 22' order by criado_em desc limit 1), 300, 300, current_date),
  ((select id from materiais where nome = 'Cateter 14' order by criado_em desc limit 1), 100, 100, current_date),
  ((select id from materiais where nome = 'Cateter 16' order by criado_em desc limit 1), 200, 200, current_date),
  ((select id from materiais where nome = 'Cateter 18' order by criado_em desc limit 1), 150, 150, current_date),
  ((select id from materiais where nome = 'Cateter 20' order by criado_em desc limit 1), 150, 150, current_date),
  ((select id from materiais where nome = 'Cateter 24' order by criado_em desc limit 1), 300, 300, current_date),
  ((select id from materiais where nome = 'Agulha 13x 0,45' order by criado_em desc limit 1), 900, 900, current_date),
  ((select id from materiais where nome = 'Agulha 40x1,20' order by criado_em desc limit 1), 600, 600, current_date),
  ((select id from materiais where nome = 'Seringa 1 ml' order by criado_em desc limit 1), 66, 66, current_date),
  ((select id from materiais where nome = 'Seringa 3 ml' order by criado_em desc limit 1), 896, 896, current_date),
  ((select id from materiais where nome = 'Seringa 60 ml' order by criado_em desc limit 1), 1, 1, current_date),
  ((select id from materiais where nome = 'Seringa 20 ml' order by criado_em desc limit 1), 195, 195, current_date),
  ((select id from materiais where nome = 'Seringa 10 ml' order by criado_em desc limit 1), 209, 209, current_date),
  ((select id from materiais where nome = 'Manitol' order by criado_em desc limit 1), 21, 21, current_date),
  ((select id from materiais where nome = 'Glicose 500 ml' order by criado_em desc limit 1), 36, 36, current_date),
  ((select id from materiais where nome = 'Álcool 70%' order by criado_em desc limit 1), 24, 24, current_date),
  ((select id from materiais where nome = 'Xylestesin Spray' order by criado_em desc limit 1), 7, 7, current_date),
  ((select id from materiais where nome = 'Lactuose' order by criado_em desc limit 1), 3, 3, current_date),
  ((select id from materiais where nome = 'Simeticona 75 mg/ml' order by criado_em desc limit 1), 60, 60, current_date),
  ((select id from materiais where nome = 'Envelope para esterilização' order by criado_em desc limit 1), 3, 3, current_date),
  ((select id from materiais where nome = 'Escovinha' order by criado_em desc limit 1), 9, 9, current_date),
  ((select id from materiais where nome = 'Equipo macrogotas' order by criado_em desc limit 1), 12, 12, current_date),
  ((select id from materiais where nome = 'Gel para ultrassom' order by criado_em desc limit 1), 3, 3, current_date),
  ((select id from materiais where nome = 'Detergente enzimático' order by criado_em desc limit 1), 5, 5, current_date),
  ((select id from materiais where nome = 'Iodo' order by criado_em desc limit 1), 1, 1, current_date),
  ((select id from materiais where nome = 'Lidocaina gel' order by criado_em desc limit 1), 60, 60, current_date),
  ((select id from materiais where nome = 'Cloreto de sódio 250 ml' order by criado_em desc limit 1), 70, 70, current_date),
  ((select id from materiais where nome = 'Soro cloreto de sódio 100 ml' order by criado_em desc limit 1), 60, 60, current_date),
  ((select id from materiais where nome = 'Soro cloreto de sódio 500 ml' order by criado_em desc limit 1), 27, 27, current_date),
  ((select id from materiais where nome = 'Água para injeção' order by criado_em desc limit 1), 2, 2, current_date),
  ((select id from materiais where nome = 'Solução Ringer com lactato 500 ml' order by criado_em desc limit 1), 60, 60, current_date),
  ((select id from materiais where nome = 'Diazepam' order by criado_em desc limit 1), 5, 5, current_date),
  ((select id from materiais where nome = 'Papel lençol' order by criado_em desc limit 1), 50, 50, current_date);
